version: '3'

services:
  db:
    image: postgres
    container_name: postgres

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: movie-database
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
